[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
core = {path = "../core"}

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false